AWSTemplateFormatVersion: 2010-09-09

Description: Battlemon backend cluster layer

Resources:
  BattlemonBackendCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: BattlemonBackendCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: BattlemonBackendCluster

Outputs:
  BattlemonBackendCluster:
    Value: !Ref BattlemonBackendCluster
    Exports:
      Name: BattlemonBackendCluster