AWSTemplateFormatVersion: 2010-09-09

Description: BattlemonAPI layer

Parameters:
  BattlemonAPIBackendECRRepositoryURI:
    Description: Battlemon backend API repository's URI of Amazon Container Registry
    Type: String
    Default: "987666890397.dkr.ecr.eu-central-1.amazonaws.com/battlemon-api:latest"

  BattlemonAPIGRPCPort:
    Description: GRPC port for Battlemon API backend
    Type: Number
    Default: 3001

  BattlemonAPILogLevel:
    Description: Log level for BattlemonAPI service
    Type: String
    Default: info

  BattlemonAPIServeSwagger:
    Description: Serve Swagger
    Type: String
    Default: true

Resources:
  BattlemonAPISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via ALB on port 3000 by default, but can be overwritten by BattlemonAPIBackendPort parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !ImportValue BattlemonAPIBackendPort
          ToPort: !ImportValue BattlemonAPIBackendPort
          CidrIp: !ImportValue BattlemonVpcCIDR
        - IpProtocol: tcp
          FromPort: !Ref BattlemonAPIGRPCPort
          ToPort: !Ref BattlemonAPIGRPCPort
          CidrIp: !ImportValue BattlemonVpcCIDR
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: BattlemonAPISecurityGroup

  BattlemonAPIBackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: BattlemonAPIBackendService
      ServiceRegistries:
        - RegistryArn: !ImportValue BattlemonAPIDiscoveryService
      Cluster: !ImportValue BattlemonBackendCluster
      TaskDefinition: !Ref BattlemonApiTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: [ !ImportValue BattlemonPrivateSubnet1, !ImportValue BattlemonPrivateSubnet2 ]
          SecurityGroups: [ !Ref BattlemonAPISecurityGroup ]
      LoadBalancers:
        - ContainerName: BattlemonAPIBackend
          ContainerPort: !ImportValue BattlemonAPIBackendPort
          TargetGroupArn: !ImportValue ALBTargetGroup
      Tags:
        - Key: Name
          Value: BattlemonAPIBackendService

  BattlemonAPIServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub
        - service/${Cluster}/${Service}
        - Cluster: !ImportValue BattlemonBackendCluster
          Service: !ImportValue BattlemonAPIBackendService
      RoleARN: !ImportValue BattlemonAutoscaleRoleArn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  BattlemonAPIServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: AStepPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref BattlemonAPIServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 1
        Cooldown: 60
        MetricAggregationType: Average

  BattlemonAPICPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ServiceName
          Value: !Sub
            - service/${Cluster}/${Service}
            - Cluster: !ImportValue BattlemonBackendCluster
              Service: !ImportValue BattlemonAPIBackendService
        - Name: ClusterName
          Value: !ImportValue BattlemonBackendCluster
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 75
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref BattlemonAPIServiceScalingPolicy
      InsufficientDataActions: [ ]

  BattlemonAPIBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/battlemon-api-backend
      RetentionInDays: 7

  BattlemonApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [ FARGATE ]
      Family: BattlemonAPIBackend
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue BattlemonTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: BattlemonAPIBackend
          Image: !Ref BattlemonAPIBackendECRRepositoryURI
          Essential: true
          PortMappings:
            - ContainerPort: !ImportValue BattlemonAPIBackendPort
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: !ImportValue BattlemonAPIBackendPort
            - Name: GRPC_PORT
              Value: !Ref BattlemonAPIGRPCPort
            - Name: DATABASE_HOST
              Value: !ImportValue BattlemonDatabaseInstanceEndpointAddress
            - Name: DATABASE_USER
              Value: !ImportValue BattlemonDatabaseUsername
            - Name: DATABASE_NAME
              Value: !ImportValue BattlemonDatabaseName
            - Name: DATABASE_PORT
              Value: !ImportValue BattlemonDatabasePort
            - Name: LOG_LEVEL
              Value: !Ref BattlemonAPILogLevel
            - Name: SERVE_SWAGGER
              Value: !Ref BattlemonAPIServeSwagger
          Secrets:
            - Name: DATABASE_PASSWORD
              ValueFrom: !ImportValue BattlemonDatabasePassword
            - Name: JWT_SECRET
              ValueFrom: !ImportValue BattlemonAPIJWTSecret
            - Name: SERVER_PRIVATE_KEY
              ValueFrom: !ImportValue BattlemonAPIServerPrivateKey
            - Name: BLOCKCHAIN_PROVIDER_API_KEY
              ValueFrom: !ImportValue BattlemonAPIBlockchainProviderApiKey
            - Name: ACCESS_KEY_CONTRACT_ADDRESS
              ValueFrom: !ImportValue AccessKeyContractAddress
            - Name: GEMS_CONTRACT_ADDRESS
              ValueFrom: !ImportValue GemsContractAddress
            - Name: REFERRAL_CONTRACT_ADDRESS
              ValueFrom: !ImportValue ReferralContractAddress
            - Name: BLOCKCHAIN_PROVIDER_URL
              ValueFrom: !ImportValue BlockchainProviderUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BattlemonAPIBackendLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: 256
      Memory: 0.5 GB
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: BattlemonAPIBackendTaskDefinition
Outputs:
  BattlemonAPIGRPCPort:
    Value: !Ref BattlemonAPIGRPCPort
    Export:
      Name: BattlemonAPIGRPCPort