AWSTemplateFormatVersion: 2010-09-09

Description: BattlemonAPI secrets layer

Resources:
  # Secrets
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonAPIJWTSecret
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonAPIJWTSecret

  ServerPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonAPIServerPrivateKey
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonAPIServerPrivateKey

  BlockchainProviderApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonAPIBlockchainProviderApiKey
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonAPIBlockchainProviderApiKey

Outputs:
  JWTSecretArn:
    Value: !Ref JWTSecret
    Export:
      Name: BattlemonAPIJWTSecret


  BattlemonAPIServerPrivateKeyArn:
    Value: !Ref ServerPrivateKey
    Export:
      Name: BattlemonAPIServerPrivateKey

  BattlemonAPIBlockchainProviderApiKeyArn:
    Value: !Ref BlockchainProviderApiKey
    Export:
      Name: BattlemonAPIBlockchainProviderApiKey