AWSTemplateFormatVersion: 2010-09-09

Description: BattlemonAPI layer

Parameters:
  BattlemonAPIBackendECRRepositoryURI:
    Description: Battlemon backend API repository's URI of Amazon Container Registry
    Type: String
    Default: "987666890397.dkr.ecr.eu-central-1.amazonaws.com/battlemon-api:latest"

  BattlemonAPIGRPCPort:
    Description: GRPC port for Battlemon API backend
    Type: Number
    Default: 3001

  BattlemonAPILogLevel:
    Description: Log level for BattlemonAPI service
    Type: String
    Default: info

  BattlemonAPIServeSwagger:
    Description: Serve Swagger
    Type: String
    Default: true

  BattlemonAPIAccessKeyContractAddress:
    Description: AccessKey contract address
    Type: String
    Default: '0x715418aD6e0CE69a5FfA72Eb34ECc04d712Cd106'

  BattlemonAPIGemsContractAddress:
    Description: Gems contract address
    Type: String
    Default: '0xeAe2c6b00C57DC313b1B6d46094fE032Fe1740e5'

  BattlemonAPIReferralContractAddress:
    Description: Referral contract address
    Type: String
    Default: '0x62c99ae88D1048d65aFF47a97f976c8F174B5Ee5'

  BattlemonAPIBlockchainProviderUrl:
    Description: Blockchain provider url
    Type: String
    Default: 'https://rpc.goerli.linea.build'

Resources:
  BattlemonAPISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via ALB on port 3000 by default, but can be overwritten by BattlemonAPIBackendPort parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !ImportValue BattlemonAPIBackendPort
          ToPort: !ImportValue BattlemonAPIBackendPort
          CidrIp: !ImportValue BattlemonVpcCIDR
        - IpProtocol: tcp
          FromPort: !Ref BattlemonAPIGRPCPort
          ToPort: !Ref BattlemonAPIGRPCPort
          CidrIp: !ImportValue BattlemonVpcCIDR
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: BattlemonAPISecurityGroup

  # BattlemonAPI service
  BattlemonAPIBackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: BattlemonAPIBackendService
      ServiceRegistries:
        - RegistryArn: !ImportValue BattlemonAPIDiscoveryService
      Cluster: !ImportValue BattlemonBackendCluster
      TaskDefinition: !Ref BattlemonApiTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: [ !ImportValue BattlemonPrivateSubnet1, !ImportValue BattlemonPrivateSubnet2 ]
          SecurityGroups: [ !Ref BattlemonAPISecurityGroup ]
      LoadBalancers:
        - ContainerName: BattlemonAPIBackend
          ContainerPort: !ImportValue BattlemonAPIBackendPort
          TargetGroupArn: !ImportValue ALBTargetGroup
      Tags:
        - Key: Name
          Value: BattlemonAPIBackendService

  BattlemonAPIBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/battlemon-api-backend
      RetentionInDays: 7

  BattlemonApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [ FARGATE ]
      Family: BattlemonAPIBackend
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue BattlemonTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: BattlemonAPIBackend
          Image: !Ref BattlemonAPIBackendECRRepositoryURI
          Essential: true
          PortMappings:
            - ContainerPort: !ImportValue BattlemonAPIBackendPort
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: !ImportValue BattlemonAPIBackendPort
            - Name: GRPC_PORT
              Value: !Ref BattlemonAPIGRPCPort
            - Name: DATABASE_HOST
              Value: !ImportValue BattlemonDatabaseInstanceEndpointAddress
            - Name: DATABASE_USER
              Value: !ImportValue BattlemonDatabaseUsername
            - Name: DATABASE_NAME
              Value: !ImportValue BattlemonDatabaseName
            - Name: DATABASE_PORT
              Value: !ImportValue BattlemonDatabasePort
            - Name: LOG_LEVEL
              Value: !Ref BattlemonAPILogLevel
            - Name: SERVE_SWAGGER
              Value: !Ref BattlemonAPIServeSwagger
            - Name: ACCESS_KEY_CONTRACT_ADDRESS
              Value: !Ref BattlemonAPIAccessKeyContractAddress
            - Name: GEMS_CONTRACT_ADDRESS
              Value: !Ref BattlemonAPIGemsContractAddress
            - Name: REFERRAL_CONTRACT_ADDRESS
              Value: !Ref BattlemonAPIReferralContractAddress
            - Name: BLOCKCHAIN_PROVIDER_URL
              Value: !Ref BattlemonAPIBlockchainProviderUrl
          Secrets:
            - Name: DATABASE_PASSWORD
              ValueFrom: !ImportValue BattlemonDatabasePassword
            - Name: JWT_SECRET
              ValueFrom: !ImportValue BattlemonAPIJWTSecret
            - Name: SERVER_PRIVATE_KEY
              ValueFrom: !ImportValue BattlemonAPIServerPrivateKey
          #            - Name: BLOCKCHAIN_PROVIDER_API_KEY
          #              ValueFrom: !ImportValue BattlemonAPIBlockchainProviderApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BattlemonAPIBackendLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: 256
      Memory: 0.5 GB
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: BattlemonAPIBackendTaskDefinition
Outputs:
  BattlemonAPIGRPCPort:
    Value: !Ref BattlemonAPIGRPCPort
    Export:
      Name: BattlemonAPIGRPCPort

  BattlemonAPIBlockchainProviderUrl:
    Value: !Ref BattlemonAPIBlockchainProviderUrl
    Export:
      Name: BattlemonAPIBlockchainProviderUrl

  BattlemonAPIAccessKeyContractAddress:
    Value: !Ref BattlemonAPIAccessKeyContractAddress
    Export:
      Name: BattlemonAPIAccessKeyContractAddress

  BattlemonAPIGemsContractAddress:
    Value: !Ref BattlemonAPIGemsContractAddress
    Export:
      Name: BattlemonAPIGemsContractAddress

  BattlemonAPIReferralContractAddress:
    Value: !Ref BattlemonAPIReferralContractAddress
    Export:
      Name: BattlemonAPIReferralContractAddress