AWSTemplateFormatVersion: 2010-09-09

Description: IAM layer

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: TaskExecutionRole

  BattlemonAutoscaleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'autoscaling:*'
            Resource: '*'
      Tags:
        - Key: Name
          Value: BattlemonAutoscaleRole

Outputs:
  TaskExecutionRoleArn:
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: BattlemonTaskExecutionRoleArn

  BattlemonAutoscaleRoleArn:
    Value: !GetAtt BattlemonAutoscaleRole.Arn
    Export:
      Name: 'BattlemonAutoscaleRoleArn'
