AWSTemplateFormatVersion: "2010-09-09"

Description:
  this is template for learning purposes. will be change to production ready later

Parameters:
  StackAlias:
    Description: Alias of the stack
    Type: String
    Default: LearningStack

Resources:
  BattlemonVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
        - Key: stack
          Value: learning

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: BattlemonVPC

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BattlemonVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BattlemonVPC
      CidrBlock: 10.1.10.0/24
      AvailabilityZone: !Select [ 0, Fn::GetAZs: !Ref "AWS::Region" ]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref StackAlias, "Public", "A" ] ]

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BattlemonVPC
      CidrBlock: 10.1.20.0/24
      AvailabilityZone: !Select [ 0, Fn::GetAZs: !Ref "AWS::Region" ]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref StackAlias, "Public", "B" ] ]

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BattlemonVPC
      CidrBlock: 10.1.50.0/24
      AvailabilityZone: !Select [ 0, Fn::GetAZs: !Ref "AWS::Region" ]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref StackAlias, "Private", "A" ] ]

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BattlemonVPC
      CidrBlock: 10.1.60.0/24
      AvailabilityZone: !Select [ 0, Fn::GetAZs: !Ref "AWS::Region" ]
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref StackAlias, "Private", "B" ] ]