Resources:
  BattlemonVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
        - Key: stack
          Value: learning
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: BattlemonVPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BattlemonVPC
      InternetGatewayId: !Ref InternetGateway