AWSTemplateFormatVersion: 2010-09-09

Description: Lemoland layer

Parameters:
  LemolandBackendPort:
    Description: Lemoland backend port
    Type: Number
    Default: 3000

  LemolandBackendECRRepositoryURI:
    Description: Lemoland backend repository's URI of Amazon Container Registry
    Type: String
    Default: "987666890397.dkr.ecr.eu-central-1.amazonaws.com/lemoland-api-nodejs:latest"

  LemolandLogLevel:
    Description: Log level for lemoland service
    Type: String
    Default: info

  LemolandServeSwagger:
    Description: Serve Swagger
    Type: String
    Default: true

  LemonlandDiscordGuildId:
    Description: Id of battlemon discord server
    Type: String
    Default: 893433519110488064

  LemolandAccessKeyContractAddress:
    Description: AccessKey contract address
    Type: String
    Default: 0x715418aD6e0CE69a5FfA72Eb34ECc04d712Cd106

  LemolandGemsContractAddress:
    Description: Gems contract address
    Type: String
    Default: 0xeAe2c6b00C57DC313b1B6d46094fE032Fe1740e5

  LemolandReferralContractAddress:
    Description: Referral contract address
    Type: String
    Default: 0x62c99ae88D1048d65aFF47a97f976c8F174B5Ee5

Resources:
  # Secrets
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: LemolandJWTSecret
      GenerateSecretString:
        SecretStringTemplate: "CHANGE ME"
      Tags:
        - Key: Name
          Value: LemolandJWTSecret

  # Application Load Balancer
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and HTTPS access on port 80/443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: ALBSecurityGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB
      SecurityGroups: [ !Ref ALBSecurityGroup ]
      Subnets: [ !ImportValue BattlemonPublicSubnet1, !ImportValue BattlemonPublicSubnet2 ]

  ALBListenerNoSslCertificate:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        #        - Type: redirect
        #          RedirectConfig:
        #            Host: "#{host}"
        #            Path: "/#{path}"
        #            Port: "443"
        #            Protocol: HTTPS
        #            StatusCode: HTTP_301
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # Implement it later when issue certs for domain
  #  ALBListenerSslCertificate:
  #    Type: AWS::ElasticLoadBalancingV2::Listener
  #    Properties:
  #      Certificates:
  #        - CertificateArn: !Ref AcmCertificate
  #      DefaultActions:
  #        - Type: forward
  #          TargetGroupArn: !Ref ALBTargetGroup
  #      LoadBalancerArn: !Ref ApplicationLoadBalancer
  #      Port: 443
  #      Protocol: HTTPS

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /healthcheck
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Port: !Ref LemolandBackendPort
      Name: LemolandBackend
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 5
      VpcId:
        !ImportValue BattlemonVpcId

  # Backend cluster
  LemolandSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via ALB on port 3000 by default, but can be overwritten by LemolandBackendPort parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref LemolandBackendPort
          ToPort: !Ref LemolandBackendPort
          CidrIp: !ImportValue BattlemonVpcCIDR
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: LemolandSecurityGroup

  LemolandBackendCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: LemolandBackendCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: LemolandBackendCluster


  # Lemoland service
  LemolandBackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: LemolandBackendService
      Cluster: !Ref LemolandBackendCluster
      TaskDefinition: !Ref LemolandTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: [ !ImportValue BattlemonPrivateSubnet1, !ImportValue BattlemonPrivateSubnet2 ]
          SecurityGroups: [ !Ref LemolandSecurityGroup ]
      LoadBalancers:
        - ContainerName: LemolandBackend
          ContainerPort: !Ref LemolandBackendPort
          TargetGroupArn: !Ref ALBTargetGroup
      Tags:
        - Key: Name
          Value: LemolandBackendService

  LemolandBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/lemoland-backend
      RetentionInDays: 7

  LemolandTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [ FARGATE ]
      Family: LemolandBackend
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue BattlemonTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: LemolandBackend
          Image: !Ref LemolandBackendECRRepositoryURI
          Essential: true
          PortMappings:
            - ContainerPort: !Ref LemolandBackendPort
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: !Ref LemolandBackendPort
            - Name: DATABASE_HOST
              Value: !ImportValue BattlemonDatabaseInstanceEndpointAddress
            - Name: DATABASE_NAME
              Value: !ImportValue BattlemonDatabaseName
            - Name: DATABASE_PORT
              Value: !ImportValue BattlemonDatabasePort
            - Name: LOG_LEVEL
              Value: !Ref LemolandLogLevel
            - Name: SERVE_SWAGGER
              Value: !Ref LemolandServeSwagger
            - Name: DISCORD_GUILD_ID
              Value: !Ref LemonlandDiscordGuildId
            - Name: ACCESS_KEY_CONTRACT_ADDRESS
              Value: !Ref LemolandAccessKeyContractAddress
            - Name: GEMS_CONTRACT_ADDRESS
              Value: !Ref LemolandGemsContractAddress
            - Name: REFERRAL_CONTRACT_ADDRESS
              Value: !Ref LemolandReferralContractAddress
          Secrets:
            - Name: DATABASE_USER
              ValueFrom: !Sub
                - '{{resolve:secretsmanager:${Arn}:SecretString:username}}'
                - Arn: !ImportValue BattlemonDatabaseSecret
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub
                - '{{resolve:secretsmanager:${Arn}:SecretString:password}}'
                - Arn: !ImportValue BattlemonDatabaseSecret
            - Name: JWT_SECRET
              Value: !Sub '{{resolve:secretsmanager:${JWTSecret}:SecretString}}'
          #            - Name: DISCORD_BOT_TOKEN
          #              Value: !Sub '{{resolve:secretsmanager:${DiscordBotTokenSecret}:SecretString}}'
          #            - Name: BLOCKCHAIN_PROVIDER_URL
          #              Value: !Sub '{{resolve:secretsmanager:${BlockchainProviderUrl}:SecretString}}'
          #            - Name: SERVER_PRIVATE_KEY
          #              Value: !Sub '{{resolve:secretsmanager:${LemolandServerPrivateKey}:SecretString}}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LemolandBackendLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: 256
      Memory: 0.5 GB
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: LemolandBackendTaskDefinition
