AWSTemplateFormatVersion: 2010-09-09

Description: Lemoland layer

Parameters:
  LemolandBackendECRRepositoryURI:
    Description: Lemoland backend repository's URI of Amazon Container Registry
    Type: String
    Default: "987666890397.dkr.ecr.eu-central-1.amazonaws.com/lemoland-api-nodejs:latest"

  LemolandLogLevel:
    Description: Log level for lemoland service
    Type: String
    Default: info

  LemolandServeSwagger:
    Description: Serve Swagger
    Type: String
    Default: true

  LemonlandDiscordGuildId:
    Description: Id of battlemon discord server
    Type: String
    Default: 893433519110488064

  LemolandAccessKeyContractAddress:
    Description: AccessKey contract address
    Type: String
    Default: '0x715418aD6e0CE69a5FfA72Eb34ECc04d712Cd106'

  LemolandGemsContractAddress:
    Description: Gems contract address
    Type: String
    Default: '0xeAe2c6b00C57DC313b1B6d46094fE032Fe1740e5'

  LemolandReferralContractAddress:
    Description: Referral contract address
    Type: String
    Default: '0x62c99ae88D1048d65aFF47a97f976c8F174B5Ee5'

  LemolandBlockchainProviderUrl:
    Description: Blockchain provider url
    Type: String
    Default: 'https://consensys-zkevm-goerli-prealpha.infura.io/v3/'

Resources:
  # Backend cluster
  LemolandSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via ALB on port 3000 by default, but can be overwritten by LemolandBackendPort parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !ImportValue LemolandBackendPort
          ToPort: !ImportValue LemolandBackendPort
          CidrIp: !ImportValue BattlemonVpcCIDR
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: LemolandSecurityGroup

  # Lemoland service
  LemolandBackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: LemolandBackendService
      Cluster: !ImportValue BattlemonBackendCluster
      TaskDefinition: !Ref LemolandTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: [ !ImportValue BattlemonPrivateSubnet1, !ImportValue BattlemonPrivateSubnet2 ]
          SecurityGroups: [ !Ref LemolandSecurityGroup ]
      LoadBalancers:
        - ContainerName: LemolandBackend
          ContainerPort: !ImportValue LemolandBackendPort
          TargetGroupArn: !ImportValue ALBTargetGroup
      Tags:
        - Key: Name
          Value: LemolandBackendService

  LemolandBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/lemoland-backend
      RetentionInDays: 7

  LemolandTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [ FARGATE ]
      Family: LemolandBackend
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue BattlemonTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: LemolandBackend
          Image: !Ref LemolandBackendECRRepositoryURI
          Essential: true
          PortMappings:
            - ContainerPort: !ImportValue LemolandBackendPort
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: !ImportValue LemolandBackendPort
            - Name: DATABASE_HOST
              Value: !ImportValue BattlemonDatabaseInstanceEndpointAddress
            - Name: DATABASE_USER
              Value: !ImportValue BattlemonDatabaseUsername
            - Name: DATABASE_NAME
              Value: !ImportValue BattlemonDatabaseName
            - Name: DATABASE_PORT
              Value: !ImportValue BattlemonDatabasePort
            - Name: LOG_LEVEL
              Value: !Ref LemolandLogLevel
            - Name: SERVE_SWAGGER
              Value: !Ref LemolandServeSwagger
            - Name: DISCORD_GUILD_ID
              Value: !Ref LemonlandDiscordGuildId
            - Name: ACCESS_KEY_CONTRACT_ADDRESS
              Value: !Ref LemolandAccessKeyContractAddress
            - Name: GEMS_CONTRACT_ADDRESS
              Value: !Ref LemolandGemsContractAddress
            - Name: REFERRAL_CONTRACT_ADDRESS
              Value: !Ref LemolandReferralContractAddress
            - Name: BLOCKCHAIN_PROVIDER_URL
              Value: !Ref LemolandBlockchainProviderUrl
          Secrets:
            - Name: DATABASE_PASSWORD
              ValueFrom: !ImportValue BattlemonDatabasePassword
            - Name: JWT_SECRET
              ValueFrom: !ImportValue LemolandJWTSecret
            - Name: DISCORD_BOT_TOKEN
              ValueFrom: !ImportValue LemolandDiscordBotToken
            - Name: SERVER_PRIVATE_KEY
              ValueFrom: !ImportValue LemolandServerPrivateKey
            - Name: BLOCKCHAIN_PROVIDER_API_KEY
              ValueFrom: !ImportValue LemolandBlockchainProviderApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LemolandBackendLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: 256
      Memory: 0.5 GB
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: LemolandBackendTaskDefinition
