AWSTemplateFormatVersion: 2010-09-09

Description: Layer with secrets for BattlemonListener service

Resources:
  DiscordBotToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonListenerDiscordBotTokenSecret
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonListenerDiscordBotTokenSecret

  PickAxeContractAddress:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonListenerPickAxeContractAddress
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonListenerPickAxeContractAddress

  GalxeAccessToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonListenerGalxeAccessToken
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonListenerGalxeAccessToken

Outputs:
  DiscordBotToken:
    Value: !Ref DiscordBotToken
    Export:
      Name: BattlemonListenerDiscordBotToken

  PickAxeContractAddress:
    Value: !Ref PickAxeContractAddress
    Export:
      Name: BattlemonListenerPickAxeContractAddress

  GalxeAccessToken:
    Value: !Ref GalxeAccessToken
    Export:
      Name: BattlemonListenerGalxeAccessToken