AWSTemplateFormatVersion: 2010-09-09

Description: Layer with secrets for BattlemonListener service

Resources:
  DiscordBotToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BattlemonListenerDiscordBotTokenSecret
      SecretString: "CHANGE_ME"
      Tags:
        - Key: Name
          Value: BattlemonListenerDiscordBotTokenSecret

Outputs:
  DiscordBotToken:
    Value: !Ref DiscordBotToken
    Export:
      Name: BattlemonListenerDiscordBotToken