AWSTemplateFormatVersion: 2010-09-09

Description: Parameters for battlemon task definitions and services

Resources:
  AccessKeyContractAddressParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /BattlemonAPI/AccessKeyContractAddress
      Type: String
      Value: '0x5106184572660c48B86e276eaA4bC7bD99f43d81'
      Description: AccessKey contract address

  GemsContractAddressParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /BattlemonAPI/GemsContractAddress
      Type: String
      Value: '0x463B24879DD0D5Dc087C452f7801509FeBe29e5D'
      Description: Gems contract address

  ReferralContractAddressParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /BattlemonAPI/ReferralContractAddress
      Type: String
      Value: '0x9307A5b9b51C3893033Ba577F6882b98405bAFcF'
      Description: Referral contract address

  BlockchainProviderUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /BattlemonAPI/BlockchainProviderUrl
      Type: String
      Value: 'https://linea-goerli.infura.io/v3/'
      Description: Blockchain provider url

  DiscordGuildIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /BattlemonListener/DiscordGuildId
      Type: String
      Value: '893433519110488064'
      Description: Battlemon Discord server's id