AWSTemplateFormatVersion: 2010-09-09

Description: Test layer

Parameters:
  TestBackendECRRepositoryURI:
    Description: Test backend repository's URI of Amazon Container Registry
    Type: String
    Default: "987666890397.dkr.ecr.eu-central-1.amazonaws.com/web3-auth-server-rust:latest"

  TestBackendPort:
    Description: Test backend port
    Type: Number
    Default: 8000

Resources:
  # Backend cluster
  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via ALB on port 8000 by default, but can be overwritten by TestBackendPort parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref TestBackendPort
          ToPort: !Ref TestBackendPort
          CidrIp: !ImportValue BattlemonVpcCIDR
      VpcId: !ImportValue BattlemonVpcId
      Tags:
        - Key: Name
          Value: TestSecurityGroup

  TestBackendCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: TestBackendCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: TestBackendCluster


  # Test service
  TestBackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: TestBackendService
      Cluster: !Ref TestBackendCluster
      TaskDefinition: !Ref TestTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: [ !ImportValue BattlemonPrivateSubnet1, !ImportValue BattlemonPrivateSubnet2 ]
          SecurityGroups: [ !Ref TestSecurityGroup ]
      LoadBalancers:
        - ContainerName: TestBackend
          ContainerPort: !Ref TestBackendPort
          TargetGroupArn: !ImportValue ALBTargetGroup
      Tags:
        - Key: Name
          Value: TestBackendService

  TestBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/test-backend
      RetentionInDays: 7

  TestTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [ FARGATE ]
      Family: TestBackend
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue BattlemonTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: TestBackend
          Image: !Ref TestBackendECRRepositoryURI
          Essential: true
          PortMappings:
            - ContainerPort: !Ref TestBackendPort
              Protocol: tcp
          Environment:
            - Name: APP_APP__HOST
              Value: "0.0.0.0"
            - Name: APP_APP__PORT
              Value: !Ref TestBackendPort
            - Name: APP_DB__HOST
              Value: !ImportValue BattlemonDatabaseInstanceEndpointAddress
            - Name: APP_DB__USERNAME
              Value: !ImportValue BattlemonDatabaseUsername
            - Name: APP_DB__DB_NAME
              Value: !ImportValue BattlemonDatabaseName
            - Name: APP_DB__PORT
              Value: !ImportValue BattlemonDatabasePort
          Secrets:
            - Name: APP_DB__PASSWORD
              ValueFrom: !ImportValue BattlemonDatabasePassword
            - Name: APP_SECRETS__KEY_PAIR
              ValueFrom: 'arn:aws:secretsmanager:eu-central-1:987666890397:secret:test-secret-irLTyi'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TestBackendLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: 256
      Memory: 0.5 GB
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: TestBackendTaskDefinition
