# arn:aws:iam::941572822749:role/cloud-formation-github-actions
# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  [ push, workflow_dispatch ]
env:
  AWS_REGION: "ap-southeast-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  cloudformation_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::941572822749:role/cloud-formation-github-actions
          role-session-name: cloudformation-github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: learning-stack
          template: learning-stack.yml
          no-fail-on-empty-changeset: "1"