name: AWS CloudFormation Deploy
on:
  [ push, workflow_dispatch ]
env:
  AWS_REGION: "eu-central-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  cloudformation_deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/test/')
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::987666890397:role/cloud-formation-github-actions-ci
          role-session-name: cloudformation-github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy vpc stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: vpc-layer-stack
          template: vpc.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy rds stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rds-layer-stack
          template: rds.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy iam stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iam-layer-stack
          template: iam.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy cluster resource to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: backend-cluster-layer-stack
          template: backend-cluster.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy SMM parameters to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: smm-parameters-layer-stack
          template: smm-parameters.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-api secrets resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: battlemon-api-secrets-layer-stack
          template: battlemon-api-secrets.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-api load-balancer resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: application-load-balancer-layer-stack
          template: alb.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon's services discovery resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: battlemon-service-discovery-layer-stack
          template: service-discovery.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-api resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: battlemon-api-service-layer-stack
          template: battlemon-api-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-listener secrets resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: listener-secrets-layer-stack
          template: listener-secrets.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-listener service resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: battlemon-listener-service-layer-stack
          template: battlemon-listener-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy battlemon-game-server service resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: battlemon-game-server-service-layer-stack
          template: battlemon-game-server-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
