name: AWS CloudFormation Deploy
on:
  [ push, workflow_dispatch ]
env:
  AWS_REGION: "eu-central-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  cloudformation_deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/test/')
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::987666890397:role/cloud-formation-github-actions-ci
          role-session-name: cloudformation-github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy vpc stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: vpc-layer-stack
          template: vpc.yml
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy rds stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rds-layer-stack
          template: rds.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy iam stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iam-layer-stack
          template: iam.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy lemoland secrets resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: lemoland-secrets-layer-stack
          template: lemoland-secrets.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy lemoland resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: application-load-balancer-layer-stack
          template: alb.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy lemoland resources to stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: lemoland-service-layer-stack
          template: lemoland-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
